/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw01_gradle;

import org.junit.jupiter.api.Test;

class HelloJavaTest {
    @Test void appHasAGreeting() {
       
    }
}
