/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw02.arrayListImpl;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class App {
    public static void main(String[] args) {
        List<String> arrayList1 = new ArrayList<>();
        for (int i = 0; i < 20; ++i) {
            arrayList1.add(getRandom());
        }
        List<String> arrayList2 = new ArrayList<>();
        arrayList2.add("Element to copy");

        List<String> DIYlist1 = new DIYarrayList<>(arrayList1);
        List<String> DIYlist2 = new DIYarrayList<>(arrayList2);

        //Checking addAll()
        Collections.addAll(arrayList1, getRandom(), getRandom());
        Collections.addAll(DIYlist1, getRandom(), getRandom());
        System.out.println("ArrayList() after addAll(): ");
        System.out.println(arrayList1);
        System.out.println("DIYArrayList() after addAll(): ");
        System.out.println(DIYlist1);

        //Checking copy
        Collections.copy(arrayList1, arrayList2);
        Collections.copy(DIYlist1, DIYlist2);
        System.out.println("ArrayList() after copy(): ");
        System.out.println(arrayList1);
        System.out.println("DIYArrayList() after copy(): ");
        System.out.println(DIYlist1);

        //Checking sort
        Collections.sort(arrayList1, null);
        Collections.sort(DIYlist1, null);
        System.out.println("ArrayList() after sort(): ");
        System.out.println(arrayList1);
        System.out.println("DIYArrayList() after sort(): ");
        System.out.println(DIYlist1);

    }

    private static String getRandom() {
        return ((Integer)((int)(Math.random()*10))).toString();
    } 
}
